### ISSUE TITLE
Failed to build twitter_streaming_location (Java)

### ISSUE THREAD

**Issue by rimms** [jubatus/jubatus-example#35]
```
$ cd jubatus-example/twitter_streaming_location/java
$ mvn compile
[INFO] Scanning for projects...
 ... snip ...
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/rimms/jubatus-example/twitter_streaming_location/java/src/main/java/example/twitterstreaminglocation/LocationClassifierApp.java:[3,46] error: cannot find symbol
[ERROR]   symbol:   class JubatusClassifierHelper
  location: package example.twitterstreaminglocation
/home/rimms/jubatus-example/twitter_streaming_location/java/src/main/java/example/twitterstreaminglocation/LocationClassifierApp.java:[3,0] error: static import only from classes and interfaces
[ERROR] /home/rimms/jubatus-example/twitter_streaming_location/java/src/main/java/example/twitterstreaminglocation/LocationTrainerApp.java:[3,46] error: cannot find symbol
[ERROR]   symbol:   class JubatusClassifierHelper
  location: package example.twitterstreaminglocation
/home/rimms/jubatus-example/twitter_streaming_location/java/src/main/java/example/twitterstreaminglocation/LocationTrainerApp.java:[3,0] error: static import only from classes and interfaces
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
 ... snip ...
```

**Comment by kmaehashi** [comment]
Oh...
I'll confirm this issue.

**Comment by kmaehashi** [comment]
This issue is a regression caused by #12 (version 0.5).

**Comment by rimms** [comment]
Fixed via #39
